-- 客户历史购买次数（per customer）
--
-- 语义：客户被判定为「成交（WON）」的次数，不是每次判定都算一次。
-- 为什么需要它：终态锁让 WON 只能进一次，而「重新激活」把客户放回 DISCOVERY，
-- 于是下一次 WON 就是一次复购 —— 这个计数和「重新激活」是一对：
--   首次成交 → purchaseCount = 1；重新激活后再成交 → 2（复购）。
--
-- 已存在的行默认 0，**不做历史回溯**：WON 的租户语义是「已成交或已到店」，
-- 无法从存量数据里可靠区分「真买了」和「只是到店」，宁可留 0 也不猜。
-- （演示数据里如果想看效果，让客户重新走一遍成交即可。）
ALTER TABLE "customer_states" ADD COLUMN "purchaseCount" INTEGER NOT NULL DEFAULT 0;
